version: "3.3"

services: 
  todo-app:
    build: .
    links:
      - todo-db
    depends_on: 
      - todo-db
    volumes:
      - todo-app:/var/www
    ports:
      - ${APP_PORT}:80
  todo-db:
    image: mysql:5.7
    hostname: ${MYSQL_HOSTNAME}
    volumes:
      - todo-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  todo-app:
  todo-db:
